---
  - name: update apt-get
    become: true
    apt: update_cache=yes cache_valid_time=3600  
    tags:
      - packages

  - name: install nginx
    become: true
    apt: pkg={{ item }} state=present
    with_items:
      - nginx
      - letsencrypt
    tags:
      - packages
      - letsencrypt

  - name: copy nginx.conf
    become: true
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    tags: 
      - nginx

  - name: setup nginx host file dirs
    become: true
    file: name="/etc/nginx/{{ item }}" state=directory owner=root group=root
    with_items:
      - sites-available
      - sites-enabled

  - name: generate diffie hellmann parameter
    become: true
    command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

  - name: ensure nginx sites have been deleted
    become: true
    file: name="/etc/nginx/sites-enabled/default" state=absent

  - name: stop nginx
    become: true
    service: name=nginx state=stopped
    tags:
      - letsencrypt

  - name: setup letsencrypt dir
    become: true
    file: name="/etc/letsencrypt" state=directory
    tags: 
      - letsencrypt

  - name: copy letsencrypt.ini
    become: true
    template: src=letsencrypt.ini dest=/etc/letsencrypt/cli.ini owner=root group=root
    tags: 
      - letsencrypt

  - name: copy letsencrypt cron job
    become: true
    template: src=le-update.sh dest=/etc/cron.monthly/letsencypt owner=root group=root mode=755
    tags: 
      - letsencrypt

  - name: create letsencrypt certificate
    become: true
    command: letsencrypt -c /etc/letsencrypt/cli.ini -d {{ site_name }} -d www.{{ site_name }} creates=/etc/letsencrypt/live/{{ site_name }}/fullchain.pem
    tags:
      - letsencrypt

  - name: start nginx
    become: true
    service: name=nginx state=started enabled=yes
    tags:
      - nginx
      - letsencrypt
