---
  - name: update apt-get
    become: true
    apt: update_cache=yes cache_valid_time=3600  
    tags:
      - packages

  - name: install nginx
    become: true
    apt: pkg=nginx state=present
    tags:
      - packages

  - name: copy nginx.conf
    become: true
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    tags: 
      - nginx

  - name: setup nginx host file dirs
    become: true
    file: name="/etc/nginx/{{ item }}" state=directory owner=root group=root
    with_items:
      - sites-available
      - sites-enabled

  - name: generate diffie hellmann parameter
    become: true
    command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

  - name: ensure nginx sites have been deleted
    become: true
    file: name="/etc/nginx/sites-enabled/default" state=absent

  - name: restart nginx
    become: true
    service: name=nginx state=reloaded enabled=yes
    tags:
      - nginx
