---
- name: Server based on Ubuntu 16.04 to run bundled Meteor Apps
  hosts: meteorServer
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson python-passlib
      tags:
        - packages
  vars:
    ssl_key: "/etc/letsencrypt/live/{{ site_name }}/privkey.pem"
    ssl_cert: "/etc/letsencrypt/live/{{ site_name }}/fullchain.pem"
  roles: 
    - common
    - nginx
    - mongo
    - nodejs
    - monitoring

- name: Server based on Ubuntu 16.04 to run PHP Apps
  hosts: phpServer
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson python-passlib
      tags:
        - packages
  vars:
    ssl_key: "/etc/letsencrypt/live/{{ site_name }}/privkey.pem"
    ssl_cert: "/etc/letsencrypt/live/{{ site_name }}/fullchain.pem"
  roles: 
    - common
    - nginx
    - amp
    - monitoring
