---
- name: Deploy meteor app
  hosts: meteorServer
  become: true
  vars:
    app_name: "meteorApp"
    deploy_dir: "/var/{{ app_name }}"
    deploy_app_dir: "/var/{{ app_name }}/{{ site_name }}"
    db_name: "{{ site_name | replace('.','') }}"
    mongo_url: "mongodb://localhost:27017/{{ db_name}}"

    nginx_upstream_name: "{{ site_name }}"
    nginx_upstream_server: "127.0.0.1:{{ port }}"
    nginx_server_proxy_pass: "http://127.0.0.1:{{ port }}"
    nginx_server_log_dir: "{{ deploy_app_dir }}"
    nginx_ssl_key: "/etc/ssl/certs/nginx.key.pem"
    nginx_ssl_cert: "/etc/ssl/certs/nginx.pem"
  
  tasks:
    - name: build meteor locally
      local_action: shell meteor build /tmp/meteor-build --server "https://{{ site_name }}:443"
      args:
        chdir: "{{ project_dir }}"
      when: project_dir is defined

    - name: copy meteor tar
      local_action: copy src="/tmp/meteor-build/{{ project_name }}.tar.gz" dest="./meteorApp.tar.gz"
      when: project_dir is defined

    - name: copy apk
      local_action: copy src="/tmp/meteor-build/android/release-unsigned.apk" dest="./meteorApp.apk"
      when: 
        - project_dir is defined
        - jarsigner_pass is defined

    - name: sign apk
      local_action: shell jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 meteorApp.apk {{ project_name }} -storepass {{ jarsigner_pass }}
      when: 
        - project_dir is defined
        - jarsigner_pass is defined

    - name: update apt packages
      become: true
      apt: update_cache=yes cache_valid_time=3600
      tags:
        - packages

    - name: System upgrade
      command: apt-get upgrade -y -qq    
      tags:
        - packages
    - name: ensure user {{ app_name }} exists
      become: true
      user: name="{{ app_name }}" state=present createhome=no system=yes

    - name: ensure directories exists
      become: true
      file: name="{{ item }}" state=directory owner="{{ app_name }}" group="www-data"
      with_items: 
      - "{{ deploy_dir }}"
      - "{{ deploy_app_dir }}"

    - name: remove current running app
      become: true
      file: name="{{ deploy_app_dir }}/bundle" state=absent

    - name: copy new bundle
      become: true
      copy: src="{{ app_name }}.tar.gz" dest="{{ deploy_app_dir }}/{{ app_name }}.tar.gz" owner={{ app_name }} group={{ app_name }}

    - name: copy android apk
      become: true
      copy: src="{{ app_name }}.apk" dest="{{ deploy_app_dir }}/{{ app_name }}.apk" owner={{ app_name }} group={{ app_name }}
      failed_when: false

    - name: unarchive new bundle
      become: true
      unarchive: src="{{ deploy_app_dir }}/{{ app_name }}.tar.gz" dest="{{ deploy_app_dir }}" remote_src=yes owner={{ app_name }} group={{ app_name }}

    - name: install npm dependencies
      become: true
      npm: path="{{ deploy_app_dir }}/bundle/programs/server"

    - name: copy nginx virtual host file
      become: true
      template: src="templates/nginx.j2" dest="/etc/nginx/sites-available/{{ site_name }}" owner=root group=root

    - name: copy systemd conf file
      become: true
      template: src="templates/systemd.j2" dest="/etc/systemd/system/{{ site_name }}.service" owner=root group=root

    - name: reload systemd
      become: true
      command: systemctl daemon-reload

    - name: start systemd service
      become: true
      service: name="{{ site_name }}" state=restarted enabled=yes
    
    - name: link nginx virtual host file
      become: true
      file: src="/etc/nginx/sites-available/{{ site_name }}" dest="/etc/nginx/sites-enabled/{{ site_name }}" state=link

    - name: restart nginx
      become: true
      service: name=nginx state=restarted