---
  - name: update apt packages
    become: true
    apt: update_cache=yes cache_valid_time=3600
    tags:
      - packages

  - name: install nodejs requirements
    become: true
    apt: pkg={{ item }} state=present
    with_items:
      - npm
    tags:
      - packages

  - name: Install Node installer using npm
    become: true
    npm: name=n global=yes state=present
    tags:
      - packages

  - name: install nodejs using n
    become: true
    shell: n v4.4.7
