---
  - name: add mongodb key
    sudo: yes
    apt_key: id=EA312927 keyserver=keyserver.ubuntu.com state=present

  - name: add mongo repo to /etc/apt/sources.list.d
    sudo: yes
    copy: src=mongodb.list dest=/etc/apt/sources.list.d/mongodb.list owner=root group=root

  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: remove old MongoDB
    sudo: yes
    apt: pkg={{ item }} state=absent
    with_items:
      - mongodb
      - mongodb-server
      - mongodb-clients

  - name: install MongoDB
    sudo: yes
    apt: pkg=mongodb-org update_cache=yes

  - name: add mongo service
    sudo: yes
    copy: src=mongodb.service dest=/etc/systemd/system/mongodb.service owner=root group=root

  - name: reload systemd
    sudo: yes
    command: systemctl daemon-reload

  - name: ensure MongoDB is running
    sudo: yes
    service: name=mongodb state=started
