---
  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: install icinga2
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - fcgiwrap
      - icinga2
      - icinga2-classicui

  - name: copy icinga2.conf for Nginx
    sudo: yes
    template: src=icinga2.conf.j2 dest=/etc/nginx/conf.d/icinga2-classicui.conf owner=root group=root

  - name: link icinga2.conf for Nginx
    sudo: yes
    file:
      src: /etc/nginx/conf.d/icinga2-classicui.conf
      dest: /etc/nginx/sites-enabled/icinga2-classicui.conf
      state: link

  - name: copy hosts.conf 
    sudo: yes
    template: src=hosts.conf.j2 dest=/etc/icinga2/conf.d/hosts.conf owner=root group=root

  - name: copy services.conf 
    sudo: yes
    template: src=services.conf.j2 dest=/etc/icinga2/conf.d/services.conf owner=root group=root

  - name: generate password for icinga UI
    sudo: yes
    htpasswd: path=/etc/icinga2-classicui/htpasswd.users name=icingaadmin password={{ monitoring_password }} owner=root group=www-data mode=0640    

  - name: ensure icinga started
    sudo: yes
    service: name=nginx enabled=yes state=started

  - name: ensure nginx reload
    sudo: yes
    service: name=nginx state=reloaded