--- 
  - name: Gathering facts
    setup:

  - name: update apt packages
    become: true
    apt: update_cache=yes cache_valid_time=3600
    tags:
      - packages

  - name: System upgrade
    command: apt-get upgrade -y -qq    
    tags:
      - packages

  - name: install basic apt packages
    become: true
    apt: pkg={{ item }} state=present
    with_items: 
      - curl
      - nano
    tags:
      - packages

  - name: configure firewall
    become: true
    ufw: state=enabled policy=deny rule=allow port={{ item }}
    with_items:
      - 22
      - 80
      - 443
    tags:
      - firewall

