--- 
  - name: update apt packages
    become: true
    apt: update_cache=yes cache_valid_time=3600
    tags:
      - packages

  - name: install Maria DB
    become: true
    apt: pkg={{ item }} state=present
    with_items: 
      - mariadb-server 
      - mariadb-client
      - python-mysqldb
    tags:
      - packages

  - name: "Ensure Backup Directory"
    become: true
    file: path='{{ backup_location }}/{{ site_name}}' state='directory' owner='root' group='root' mode=775

  - name: copy backup script to cron dir
    become: true
    template: src="templates/backup.sh" dest="/etc/cron.daily/mariadbBackup" owner=root group=root mode='755'
    when: external_storage is defined
    
  - name: restart cron
    become: true
    service: name=cron state=restarted


  - name: install PHP
    become: true
    apt: pkg={{ item }} state=present
    with_items: 
      - php7.0-fpm 
      - php7.0-cli
      - php7.0-common 
      - php7.0-mysql 
      - php7.0-curl 
      - php7.0-gd 
      - php7.0-opcache 
      - php7.0-intl 
      - php-imagick 
      - php-zip 
      - php-imap
      - php-dompdf
      - php7.0-imap 
      - php7.0-mcrypt 
      - php-memcache  
      - php7.0-pspell 
      - php7.0-recode 
      - php7.0-tidy 
      - php7.0-mbstring 
      - php7.0-xml 
      - php7.0-xmlrpc 
      - php7.0-xsl 
      - php-gettext
      - php-apcu
    tags:
      - packages

  - name: copy nginx virtual host file
    become: true
    template: src="templates/nginx-php.conf" dest="/etc/nginx/sites-available/{{ site_name }}" owner=root group=root
    tags:
    - php

  - block:
    - name: link nginx virtual host file
      become: true
      file: src="/etc/nginx/sites-available/{{ site_name }}" dest="/etc/nginx/sites-enabled/{{ site_name }}" state=link
    - name: restart nginx
      become: true
      service: name=nginx state=reloaded
    rescue:
      - name: unlink failing nginx virtual host file
        become: true
        file: src="/etc/nginx/sites-available/{{ site_name }}" dest="/etc/nginx/sites-enabled/{{ site_name }}" state=absent
    tags:
    - php

  - name: restart php-fpm
    become: true
    service: name=php7.0-fpm state=reloaded
    tags:
    - php

